// AUTO-GENERATED by scripts/prepare_skin_studio.py — do not edit by hand.

export interface SpriteInfo { w: number; h: number; frames: string[] }

export const SPRITES: Record<string, SpriteInfo> = {
  'Bg': { w: 27, h: 1920, frames: ['/sprites/Bg-f00.png'] },
  'BlackBg': { w: 250, h: 250, frames: ['/sprites/BlackBg-f00.png'] },
  'Block': { w: 129, h: 129, frames: ['/sprites/Block-f00.png', '/sprites/Block-f01.png', '/sprites/Block-f02.png', '/sprites/Block-f03.png', '/sprites/Block-f04.png', '/sprites/Block-f05.png', '/sprites/Block-f06.png', '/sprites/Block-f07.png'] },
  'BlockBelow': { w: 129, h: 129, frames: ['/sprites/BlockBelow-f00.png', '/sprites/BlockBelow-f01.png', '/sprites/BlockBelow-f02.png', '/sprites/BlockBelow-f03.png', '/sprites/BlockBelow-f04.png', '/sprites/BlockBelow-f05.png', '/sprites/BlockBelow-f06.png', '/sprites/BlockBelow-f07.png'] },
  'BlockShadow': { w: 131, h: 131, frames: ['/sprites/BlockShadow-f00.png'] },
  'Board': { w: 994, h: 994, frames: ['/sprites/Board-f00.png'] },
  'BtnClose': { w: 84, h: 84, frames: ['/sprites/BtnClose-f00.png'] },
  'BtnGOReset': { w: 332, h: 115, frames: ['/sprites/BtnGOReset-f00.png'] },
  'BtnHome': { w: 282, h: 115, frames: ['/sprites/BtnHome-f00.png'] },
  'BtnMusic': { w: 210, h: 100, frames: ['/sprites/BtnMusic-f00.png', '/sprites/BtnMusic-f01.png'] },
  'BtnMusic2': { w: 134, h: 134, frames: ['/sprites/BtnMusic2-f00.png', '/sprites/BtnMusic2-f01.png'] },
  'BtnPause': { w: 104, h: 104, frames: ['/sprites/BtnPause-f00.png'] },
  'BtnPlay': { w: 336, h: 119, frames: ['/sprites/BtnPlay-f00.png'] },
  'BtnRanking': { w: 134, h: 134, frames: ['/sprites/BtnRanking-f00.png'] },
  'BtnReset': { w: 286, h: 120, frames: ['/sprites/BtnReset-f00.png'] },
  'BtnRevive': { w: 332, h: 115, frames: ['/sprites/BtnRevive-f00.png'] },
  'BtnSFX': { w: 210, h: 100, frames: ['/sprites/BtnSFX-f00.png', '/sprites/BtnSFX-f01.png'] },
  'BtnSFX2': { w: 136, h: 136, frames: ['/sprites/BtnSFX2-f00.png', '/sprites/BtnSFX2-f01.png'] },
  'BtnShowRanking': { w: 280, h: 114, frames: ['/sprites/BtnShowRanking-f00.png'] },
  'Cheerful': { w: 50, h: 50, frames: ['/sprites/Cheerful-f00.png', '/sprites/Cheerful-f01.png', '/sprites/Cheerful-f02.png', '/sprites/Cheerful-f03.png', '/sprites/Cheerful-f04.png', '/sprites/Cheerful-f05.png', '/sprites/Cheerful-f06.png'] },
  'CircleGlow': { w: 305, h: 305, frames: ['/sprites/CircleGlow-f00.png'] },
  'ComboGlow1': { w: 382, h: 382, frames: ['/sprites/ComboGlow1-f00.png'] },
  'ComboGlow2': { w: 405, h: 405, frames: ['/sprites/ComboGlow2-f00.png'] },
  'ComboSprite': { w: 463, h: 154, frames: ['/sprites/ComboSprite-f00.png'] },
  'CupIcon': { w: 354, h: 354, frames: ['/sprites/CupIcon-f00.png'] },
  'EarnedScoreGlow': { w: 329, h: 171, frames: ['/sprites/EarnedScoreGlow-f00.png'] },
  'GameOver': { w: 469, h: 78, frames: ['/sprites/GameOver-f00.png'] },
  'GlowEffect': { w: 272, h: 172, frames: ['/sprites/GlowEffect-f00.png'] },
  'Hand': { w: 228, h: 186, frames: ['/sprites/Hand-f00.png'] },
  'Heart': { w: 304, h: 304, frames: ['/sprites/Heart-f00.png'] },
  'ItemBg': { w: 737, h: 107, frames: ['/sprites/ItemBg-f00.png', '/sprites/ItemBg-f01.png'] },
  'LeaderboardPopup2': { w: 493, h: 502, frames: ['/sprites/LeaderboardPopup2-f00.png'] },
  'LightBlueBg': { w: 10, h: 1000, frames: ['/sprites/LightBlueBg-f00.png'] },
  'LineEffect': { w: 200, h: 100, frames: ['/sprites/LineEffect-f00.png'] },
  'NoSpaceLeft': { w: 609, h: 180, frames: ['/sprites/NoSpaceLeft-f00.png'] },
  'Particles': { w: 80, h: 80, frames: ['/sprites/Particles-f00.png'] },
  'PausePopup': { w: 890, h: 1117, frames: ['/sprites/PausePopup-f00.png'] },
  'PlaceHolder': { w: 250, h: 250, frames: ['/sprites/PlaceHolder-f00.png'] },
  'RadialProgress': { w: 56, h: 56, frames: ['/sprites/RadialProgress-f00.png'] },
  'ReviveCircle': { w: 237, h: 237, frames: ['/sprites/ReviveCircle-f00.png'] },
  'Spot': { w: 120, h: 120, frames: ['/sprites/Spot-f00.png'] },
  'Sprite2': { w: 841, h: 892, frames: ['/sprites/Sprite2-f00.png'] },
  'SquareEffect': { w: 54, h: 54, frames: ['/sprites/SquareEffect-f00.png'] },
  'TLabel': { w: 146, h: 45, frames: ['/sprites/TLabel-f00.png', '/sprites/TLabel-f01.png'] },
  'txtBestScore': { w: 1024, h: 128, frames: ['/sprites/txtBestScore-f00.png'] },
  'txtComboNum': { w: 700, h: 400, frames: ['/sprites/txtComboNum-f00.png'] },
  'txtEarnedScore': { w: 512, h: 128, frames: ['/sprites/txtEarnedScore-fixed.png'] },
  'txtGOBestScore': { w: 1024, h: 128, frames: ['/sprites/txtGOBestScore-f00.png'] },
  'txtGOScore': { w: 1024, h: 128, frames: ['/sprites/txtGOScore-f00.png'] },
  'txtReviveTimer': { w: 1024, h: 128, frames: ['/sprites/txtReviveTimer-f00.png'] },
  'txtScore': { w: 1024, h: 128, frames: ['/sprites/txtScore-f00.png'] },
};

export const AUDIO_FILES: string[] = [
'beep', 'lose', 'music', 'no_space', 'put', 'return', 'revive', 'score', 'whoosh', 'score/s1', 'score/s10', 'score/s11', 'score/s13', 'score/s14', 'score/s15', 'score/s2', 'score/s3', 'score/s4', 'score/s5', 'score/s6', 'score/s7', 'score/s8', 'score/s9', 'cheerful/c2', 'cheerful/c3', 'cheerful/c4', 'cheerful/c5', 'cheerful/c6'
];

export const PROBED = {
  "bgTop": "#4259A5",
  "bgMid": "#425D9E",
  "bgBottom": "#334D8E",
  "boardCorner": "#000000",
  "boardCell00": "#18244A",
  "boardCellCenter": "#18244A",
  "boardBetween": "#18244A",
  "btnPlayAvg": "#F0AE34",
  "btnPlayCenter": "#DD950F",
  "heartAvg": "#DA6EEE",
  "cupAvg": "#F3BF08",
  "txtScoreGlyph": "#ECECEC",
  "logoAvg": "#9281DC",
  "pausePopupAvg": "#4259B5",
  "trayPhAvg": "#000000"
} as const;

export const RANKING_ROWS: { name: string; score: number }[] = [{"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}, {"name": "?", "score": 0}];

export const SHAPES: number[][][] = [[[0, 0]], [[0, 0], [1, 0], [1, 1]], [[0, 1], [1, 0], [1, 1]], [[0, 0], [0, 1], [1, 1]], [[0, 0], [0, 1], [1, 0]], [[0, 0], [0, 1], [0, 2], [1, 0]], [[0, 0], [0, 1], [1, 1], [2, 1]], [[0, 2], [1, 0], [1, 1], [1, 2]], [[0, 0], [1, 0], [2, 0], [2, 1]], [[0, 0], [0, 1], [0, 2], [1, 2]], [[0, 1], [1, 1], [2, 0], [2, 1]], [[0, 0], [1, 0], [1, 1], [1, 2]], [[0, 0], [0, 1], [1, 0], [2, 0]], [[0, 0], [0, 1], [0, 2], [1, 0], [2, 0]], [[0, 0], [0, 1], [0, 2], [1, 2], [2, 2]], [[0, 2], [1, 2], [2, 0], [2, 1], [2, 2]], [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2]], [[0, 0], [0, 1]], [[0, 0], [1, 0]], [[0, 0], [0, 1], [0, 2]], [[0, 0], [1, 0], [2, 0]], [[0, 0], [0, 1], [0, 2], [0, 3]], [[0, 0], [1, 0], [2, 0], [3, 0]], [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4]], [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0]], [[0, 0], [0, 1], [1, 0], [1, 1]], [[0, 0], [0, 1], [1, 0], [1, 1], [2, 0], [2, 1]], [[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2]], [[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]], [[0, 0], [0, 1], [0, 2], [1, 1]], [[0, 1], [1, 0], [1, 1], [2, 1]], [[0, 1], [1, 0], [1, 1], [1, 2]], [[0, 0], [1, 0], [1, 1], [2, 0]], [[0, 0], [0, 1], [1, 1], [1, 2]], [[0, 1], [1, 0], [1, 1], [2, 0]], [[0, 1], [0, 2], [1, 0], [1, 1]], [[0, 0], [1, 0], [1, 1], [2, 1]]];
