// Glossy theme engine — derive a complete board/background/tray color scheme
// from ONE base color and recolor the extracted red-cell tile at runtime.
//
// The derivation mirrors scripts/make_glossy_tiles.py::glossy_theme_colors
// (offline tile generator) so bundled preset tiles == runtime color-sphere
// recolor for the same base hex. Keep the two in sync!

import { darken, hexToRgb, lighten, mix, rgbToHsl } from './color';

/** the tile extracted from the red mockup — hue 352, monochrome red family */
export const GLOSSY_SRC_TILE = '/textures/red-cell.png';
const SRC_HUE = 352;

export interface GlossyColors {
  base: string;
  bgTop: string;
  bgBottom: string;
  plate: string;
  cell: string;
  line: string;
  tray: string;
  iconBtn: string;
  iconIconColor: string;
  popupStyle: 'light' | 'dark';
  popupC1: string;
  scoreColor: string;
  scoreStroke: string;
  bestColor: string;
  flash: string;
  comboGlow: string;
  /** HSV remap params for the cell tile (see recolorGlossyTile) */
  tileDelta: number;
  tileSat: number;
  tileVLo: number;
  tileVHi: number;
}

/** Full color scheme from one base hex. Mirrors the Python generator. */
export function glossyThemeColors(base: string): GlossyColors {
  const { h, s, l } = rgbToHsl(base); // s, l in 0–100
  const light = l > 66;
  const dark = l < 22;

  let vLo = 0.22;
  let vHi = 0.95;
  if (light) [vLo, vHi] = [0.42, 0.99];
  else if (dark) [vLo, vHi] = [0.10, 0.62];
  else if (l < 45) [vLo, vHi] = [0.15, 0.92];

  // chromatic bases keep the source saturation; low-sat bases target
  // body S = base S (slate/pastel look), floor 0.06 for clean nero/bianco
  const tileSat = s >= 50 ? 1.0 : Math.min(1.0, Math.max(0.06, s / 100) / 0.96);

  return {
    base,
    bgTop: light ? lighten(base, 0.35) : darken(base, 0.07),
    bgBottom: darken(base, light ? 0.22 : 0.40),
    plate: darken(base, 0.64),
    cell: darken(base, 0.42),
    line: darken(base, 0.72),
    tray: darken(base, 0.70),
    iconBtn: darken(base, 0.22),
    iconIconColor: light ? '#3A3E48' : '#FFFFFF',
    popupStyle: light ? 'light' : 'dark',
    popupC1: light ? lighten(base, 0.55) : darken(base, 0.72),
    scoreColor: light ? '#2E3238' : '#FFFFFF',
    scoreStroke: light ? '#FFFFFF' : darken(base, 0.75),
    bestColor: light ? '#C08A00' : '#FFD75E',
    flash: mix(base, '#FFFFFF', 0.85),
    comboGlow: lighten(base, 0.18),
    tileDelta: ((h - SRC_HUE + 540) % 360) - 180,
    tileSat,
    tileVLo: vLo,
    tileVHi: vHi,
  };
}

// ------------------------------------------------------------ variants -----

export interface GlossyVariantDef {
  id: string;       // preset id in skin.ts
  name: string;     // short Italian name shown in the picker
  base: string;     // theme base hex
  tile: string;     // bundled recolored tile (generated by make_glossy_tiles.py)
}

/** The 13 recolored variants (Rosso is the source preset 'rossoGlossy'). */
export const GLOSSY_VARIANTS: GlossyVariantDef[] = [
  { id: 'glossyNero', name: 'Nero', base: '#2B2D33', tile: '/textures/glossy-cell-nero.png' },
  { id: 'glossyBianco', name: 'Bianco', base: '#EFEFF2', tile: '/textures/glossy-cell-bianco.png' },
  { id: 'glossyViola', name: 'Viola', base: '#7A2BD6', tile: '/textures/glossy-cell-viola.png' },
  { id: 'glossyGiallo', name: 'Giallo', base: '#F5C400', tile: '/textures/glossy-cell-giallo.png' },
  { id: 'glossyVerdeChiaro', name: 'Verde chiaro', base: '#7ED957', tile: '/textures/glossy-cell-verdechiaro.png' },
  { id: 'glossyAzzurro', name: 'Azzurro', base: '#55C1F2', tile: '/textures/glossy-cell-azzurro.png' },
  { id: 'glossyBlu', name: 'Blu reale', base: '#3D5AF1', tile: '/textures/glossy-cell-blu.png' },
  { id: 'glossyArancio', name: 'Arancione', base: '#FF8A00', tile: '/textures/glossy-cell-arancio.png' },
  { id: 'glossyRosa', name: 'Rosa', base: '#EE4E94', tile: '/textures/glossy-cell-rosa.png' },
  { id: 'glossyTeal', name: 'Teal', base: '#00A99D', tile: '/textures/glossy-cell-teal.png' },
  { id: 'glossyVerde', name: 'Verde', base: '#23B04A', tile: '/textures/glossy-cell-verde.png' },
  { id: 'glossyFucsia', name: 'Fucsia', base: '#D63DE0', tile: '/textures/glossy-cell-fucsia.png' },
  { id: 'glossyGrigio', name: 'Grigio', base: '#707A8C', tile: '/textures/glossy-cell-grigio.png' },
];

/** Rosso entry shown first in pickers (uses the original extracted tile). */
export const GLOSSY_ROSSO: GlossyVariantDef = {
  id: 'rossoGlossy', name: 'Rosso', base: '#C0152A', tile: GLOSSY_SRC_TILE,
};

// ------------------------------------------------------ runtime recolor ----

function rgbToHsvPx(r: number, g: number, b: number): [number, number, number] {
  const mx = Math.max(r, g, b);
  const mn = Math.min(r, g, b);
  const d = mx - mn;
  let h = 0;
  if (d !== 0) {
    if (mx === r) h = (((g - b) / d) % 6) * 60;
    else if (mx === g) h = ((b - r) / d + 2) * 60;
    else h = ((r - g) / d + 4) * 60;
    if (h < 0) h += 360;
  }
  return [h, mx === 0 ? 0 : d / mx, mx / 255];
}

function hsvToRgbPx(h: number, s: number, v: number): [number, number, number] {
  const hp = (((h % 360) + 360) % 360) / 60;
  const c = v * s;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r = 0, g = 0, b = 0;
  if (hp < 1) [r, g, b] = [c, x, 0];
  else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x];
  else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = v - c;
  return [r + m, g + m, b + m];
}

let cachedTile: { key: string; url: string } | null = null;

/**
 * Recolor the red source tile via HSV rotate + sat scale + value remap and
 * return a PNG data URL. Same math as scripts/make_glossy_tiles.py.
 */
export function recolorGlossyTile(c: GlossyColors): Promise<string> {
  const key = `${c.tileDelta}|${c.tileSat}|${c.tileVLo}|${c.tileVHi}`;
  if (cachedTile && cachedTile.key === key) return Promise.resolve(cachedTile.url);
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const cv = document.createElement('canvas');
        cv.width = img.naturalWidth || 256;
        cv.height = img.naturalHeight || 256;
        const ctx = cv.getContext('2d', { willReadFrequently: true });
        if (!ctx) throw new Error('no 2d context');
        ctx.drawImage(img, 0, 0, cv.width, cv.height);
        const data = ctx.getImageData(0, 0, cv.width, cv.height);
        const d = data.data;
        for (let i = 0; i < d.length; i += 4) {
          const [h, s, v] = rgbToHsvPx(d[i], d[i + 1], d[i + 2]);
          const [r, g, b] = hsvToRgbPx(
            h + c.tileDelta,
            Math.min(1, s * c.tileSat),
            c.tileVLo + (c.tileVHi - c.tileVLo) * v,
          );
          d[i] = Math.round(r * 255);
          d[i + 1] = Math.round(g * 255);
          d[i + 2] = Math.round(b * 255);
        }
        ctx.putImageData(data, 0, 0);
        const url = cv.toDataURL('image/png');
        cachedTile = { key, url };
        resolve(url);
      } catch (e) {
        reject(e);
      }
    };
    img.onerror = () => reject(new Error('tile load failed'));
    img.src = GLOSSY_SRC_TILE;
  });
}

// ---------------------------------------------------- skin state entries ---

/** Theme paths (background, board, trays, buttons, texts) for a Glossy skin. */
export function glossyEntries(c: GlossyColors, tile: string): [string, unknown][] {
  return [
    ['background.style', 'gradient'],
    ['background.c1', c.bgTop],
    ['background.c2', c.bgBottom],
    ['background.vignette', 35],
    ['background.decor', 'none'],
    ['background.img', null],
    ['background.imgDim', 0],
    ['board.style', 'dark'],
    ['board.frameColor', c.plate],
    ['board.cellColor', c.cell],
    ['board.lineColor', c.line],
    ['board.radius', 36],
    ['board.cellImg', tile],
    ['tray.style', 'dark'],
    ['tray.color', c.tray],
    ['tray.opacity', 88],
    ['tray.img', null],
    ['playBtn.style', 'rounded'],
    ['playBtn.c1', '#FFC93D'],
    ['playBtn.c2', '#F57C00'],
    ['playBtn.textColor', '#FFFFFF'],
    ['playBtn.glow', 45],
    ['iconBtn.style', 'rounded'],
    ['iconBtn.bg', c.iconBtn],
    ['iconBtn.iconColor', c.iconIconColor],
    ['popup.style', c.popupStyle],
    ['popup.c1', c.popupC1],
    ['logo.style', 'text'],
    ['logo.text', 'BLOCK BLAST'],
    ['logo.font', 'lilita'],
    ['logo.c1', '#FFE49B'],
    ['logo.c2', '#F0A50E'],
    ['logo.gradient', true],
    ['logo.stroke', '#3A0208'],
    ['logo.strokeWidth', 14],
    ['logo.shadow', 55],
    ['score.style', 'css'],
    ['score.font', 'riffic'],
    ['score.color', c.scoreColor],
    ['score.c2', c.scoreColor],
    ['score.gradient', false],
    ['score.stroke', c.scoreStroke],
    ['score.strokeWidth', 4],
    ['best.color', c.bestColor],
    ['plus100.style', 'classic'],
    ['plus100.color', c.scoreColor],
    ['plus100.glow', c.bestColor],
    ['combo.color', c.bestColor],
    ['combo.glow', c.comboGlow],
    ['effects.flashColor', c.flash],
    ['effects.particles', 'confetti'],
    ['effects.comboGlow', c.bestColor],
  ];
}

/** The mockup candy blocks (choco-shot tiles) — shared by all Glossy presets. */
export function glossyBlocksEntries(): [string, unknown][] {
  return [
    ['blocks.style', 'image'],
    ['blocks.radius', 14],
    ['blocks.gap', 4],
    ['blocks.colors', ['#C42E49', '#ECB020', '#636F02', '#4D1902', '#E15202', '#3A1302', '#02A07E', '#C32E49']],
    ['blocks.img', {
      mode: 'perColor',
      single: null,
      perColor: [
        '/textures/choco-shot-0.png', '/textures/choco-shot-1.png',
        '/textures/choco-shot-2.png', '/textures/choco-shot-3.png',
        '/textures/choco-shot-4.png', '/textures/choco-shot-5.png',
        '/textures/choco-shot-6.png', '/textures/choco-shot-7.png',
      ],
      tint: false,
      fit: 'fill',
      shadow: 40,
    }],
  ];
}

/** Convert [path, value] entries into a nested override object (for merge()). */
export function entriesToOver(entries: [string, unknown][]): Record<string, unknown> {
  const root: Record<string, unknown> = {};
  for (const [path, value] of entries) {
    const keys = path.split('.');
    let cur = root;
    for (let i = 0; i < keys.length - 1; i++) {
      const k = keys[i];
      if (typeof cur[k] !== 'object' || cur[k] === null || Array.isArray(cur[k])) cur[k] = {};
      cur = cur[k] as Record<string, unknown>;
    }
    cur[keys[keys.length - 1]] = value;
  }
  return root;
}

/**
 * Recolor the current skin's theme from any base color (the "color sphere"
 * feature): derives all flat colors, recolors the cell tile on a canvas and
 * writes everything through setIn. Blocks are only touched when asked.
 */
export async function applyGlossyTheme(
  setIn: (path: string, value: unknown) => void,
  base: string,
  parts: { theme?: boolean; blocks?: boolean } = { theme: true, blocks: false },
): Promise<void> {
  const c = glossyThemeColors(base);
  if (parts.theme) {
    const tile = await recolorGlossyTile(c);
    for (const [p, v] of glossyEntries(c, tile)) setIn(p, v);
  }
  if (parts.blocks) {
    for (const [p, v] of glossyBlocksEntries()) setIn(p, v);
  }
}
